/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp3ejercicio5;

import java.awt.Component;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class AgregarClienteView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarClienteView
     */
    public AgregarClienteView() {
        initComponents();
        llenarComboCiudades();
    }

    private void llenarComboCiudades() {
        jcbCiudad.removeAllItems();
        jcbCiudad.addItem(null);

        for (String ciudad : Panel_tp5_ej1.Ciudades) {
            jcbCiudad.addItem(ciudad);
        }

        jcbCiudad.setSelectedIndex(0);
    }

    public boolean validaCamposVacios(JPanel panel) {
        for (Component comp : panel.getComponents()) {
            if (comp instanceof JTextField) {
                JTextField txt = (JTextField) comp;
                if (txt.getText().trim().isEmpty()) {
                    return false;
                }
            } else if (comp instanceof JComboBox) {
                JComboBox combo = (JComboBox) comp;
                Object selected = combo.getSelectedItem();
                if (selected == null || selected.toString().trim().isEmpty()) {
                    return false;
                }
            }
        }

        return true;
    }

    public void limpiarCampos(JPanel panel) {
        for (Component c : panel.getComponents()) {
            if (c instanceof JTextField) {
                JTextField caja = (JTextField) c;
                caja.setText("");
            } else if (c instanceof JComboBox) {
                JComboBox combo = (JComboBox) c;
                combo.setSelectedItem(null);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jpAgregarCliente = new javax.swing.JPanel();
        jlbAgregarCliente = new javax.swing.JLabel();
        jpDatos = new javax.swing.JPanel();
        jlbDni = new javax.swing.JLabel();
        jlbNombre = new javax.swing.JLabel();
        jlbapellido = new javax.swing.JLabel();
        jlbCiudad = new javax.swing.JLabel();
        jlbDomicilio = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        jcbCiudad = new javax.swing.JComboBox<>();
        jpTelefono = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setPreferredSize(new java.awt.Dimension(422, 500));

        jpAgregarCliente.setBackground(java.awt.Color.lightGray);

        jlbAgregarCliente.setBackground(java.awt.Color.lightGray);
        jlbAgregarCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbAgregarCliente.setForeground(java.awt.Color.black);
        jlbAgregarCliente.setText("Agregar Cliente");

        jpDatos.setBackground(java.awt.Color.lightGray);
        jpDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbDni.setBackground(java.awt.Color.lightGray);
        jlbDni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbDni.setForeground(java.awt.Color.black);
        jlbDni.setText("DNI:");

        jlbNombre.setBackground(java.awt.Color.lightGray);
        jlbNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbNombre.setForeground(java.awt.Color.black);
        jlbNombre.setText("Nombre:");

        jlbapellido.setBackground(java.awt.Color.lightGray);
        jlbapellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbapellido.setForeground(java.awt.Color.black);
        jlbapellido.setText("Apellido:");

        jlbCiudad.setBackground(java.awt.Color.lightGray);
        jlbCiudad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbCiudad.setForeground(java.awt.Color.black);
        jlbCiudad.setText("Ciudad:");

        jlbDomicilio.setBackground(java.awt.Color.lightGray);
        jlbDomicilio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbDomicilio.setForeground(java.awt.Color.black);
        jlbDomicilio.setText("Domicilio:");

        txtDni.setBackground(java.awt.SystemColor.control);
        txtDni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDni.setForeground(java.awt.Color.black);

        txtNombre.setBackground(java.awt.SystemColor.control);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombre.setForeground(java.awt.Color.black);

        txtApellido.setBackground(java.awt.SystemColor.control);
        txtApellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtApellido.setForeground(java.awt.Color.black);

        txtDomicilio.setBackground(java.awt.SystemColor.control);
        txtDomicilio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDomicilio.setForeground(java.awt.Color.black);

        jcbCiudad.setBackground(java.awt.Color.white);
        jcbCiudad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcbCiudad.setForeground(java.awt.Color.black);

        javax.swing.GroupLayout jpDatosLayout = new javax.swing.GroupLayout(jpDatos);
        jpDatos.setLayout(jpDatosLayout);
        jpDatosLayout.setHorizontalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbCiudad)
                    .addComponent(jlbapellido)
                    .addComponent(jlbNombre)
                    .addComponent(jlbDni)
                    .addComponent(jlbDomicilio))
                .addGap(34, 34, 34)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jpDatosLayout.setVerticalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbDni))
                .addGap(18, 18, 18)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNombre))
                .addGap(18, 18, 18)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbapellido))
                .addGap(18, 18, 18)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCiudad))
                .addGap(18, 18, 18)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbDomicilio))
                .addGap(30, 30, 30))
        );

        jpTelefono.setBackground(java.awt.Color.lightGray);
        jpTelefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setBackground(java.awt.Color.black);
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Teléfono:");

        txtTelefono.setBackground(java.awt.SystemColor.control);
        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelefono.setForeground(java.awt.Color.black);
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpTelefonoLayout = new javax.swing.GroupLayout(jpTelefono);
        jpTelefono.setLayout(jpTelefonoLayout);
        jpTelefonoLayout.setHorizontalGroup(
            jpTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelefonoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTelefonoLayout.setVerticalGroup(
            jpTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelefonoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jpTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnGuardar.setBackground(java.awt.Color.lightGray);
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setForeground(java.awt.Color.black);
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(java.awt.Color.lightGray);
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setForeground(java.awt.Color.black);
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAgregarClienteLayout = new javax.swing.GroupLayout(jpAgregarCliente);
        jpAgregarCliente.setLayout(jpAgregarClienteLayout);
        jpAgregarClienteLayout.setHorizontalGroup(
            jpAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgregarClienteLayout.createSequentialGroup()
                .addGroup(jpAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAgregarClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpAgregarClienteLayout.createSequentialGroup()
                        .addGroup(jpAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAgregarClienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jpDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpAgregarClienteLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jlbAgregarCliente)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpAgregarClienteLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        jpAgregarClienteLayout.setVerticalGroup(
            jpAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgregarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbAgregarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAgregarClienteLayout.createSequentialGroup()
                        .addComponent(jpDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAgregarClienteLayout.createSequentialGroup()
                        .addGroup(jpAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalir)
                            .addComponent(btnGuardar))
                        .addGap(62, 62, 62))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!validaCamposVacios(jpDatos) || !validaCamposVacios(jpTelefono)) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos para agregar Cliente.", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int dni = Integer.parseInt(txtDni.getText().trim());
            String nombre = txtNombre.getText().trim();
            String apellido = txtApellido.getText().trim();
            String ciudad = jcbCiudad.getSelectedItem().toString();
            String domicilio = txtDomicilio.getText().trim();
            long telefono = Long.parseLong(txtTelefono.getText().trim());

            Contacto nuevo = new Contacto(dni, nombre, apellido, ciudad, domicilio);

            Panel_tp5_ej1.directorio.agregarContacto(telefono, nuevo);

            JOptionPane.showMessageDialog(this, "El cliente se agregó correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            limpiarCampos(jpDatos);
            limpiarCampos(jpTelefono);
            llenarComboCiudades();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El DNI y el Teléfono deben ser números.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jcbCiudad;
    private javax.swing.JLabel jlbAgregarCliente;
    private javax.swing.JLabel jlbCiudad;
    private javax.swing.JLabel jlbDni;
    private javax.swing.JLabel jlbDomicilio;
    private javax.swing.JLabel jlbNombre;
    private javax.swing.JLabel jlbapellido;
    private javax.swing.JPanel jpAgregarCliente;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JPanel jpTelefono;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
