/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp3ejercicio5;

import java.util.Set;
import java.util.TreeSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Panel_tp5_ej1 extends javax.swing.JFrame {

    public static DirectorioTelefonico directorio = new DirectorioTelefonico();
    public static Set<String> Ciudades = new TreeSet<>();

    public Panel_tp5_ej1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jmVistaPrincipal = new javax.swing.JMenuBar();
        jmClientes = new javax.swing.JMenu();
        AgregarCliente = new javax.swing.JMenuItem();
        BuscarCliente = new javax.swing.JMenuItem();
        BorrarCliente = new javax.swing.JMenuItem();
        jmDirectorio = new javax.swing.JMenu();
        BuscarClienteporCiudad = new javax.swing.JMenuItem();
        BuscarTelefono = new javax.swing.JMenuItem();
        jmCiudades = new javax.swing.JMenu();
        AgregarCiudad = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1088, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        jmClientes.setText("Clientes");
        jmClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmClientesActionPerformed(evt);
            }
        });

        AgregarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        AgregarCliente.setText("Agregar Cliente");
        AgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarClienteActionPerformed(evt);
            }
        });
        jmClientes.add(AgregarCliente);

        BuscarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        BuscarCliente.setText("Buscar Cliente");
        BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarClienteActionPerformed(evt);
            }
        });
        jmClientes.add(BuscarCliente);

        BorrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        BorrarCliente.setText("Borrar Cliente");
        BorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarClienteActionPerformed(evt);
            }
        });
        jmClientes.add(BorrarCliente);

        jmVistaPrincipal.add(jmClientes);

        jmDirectorio.setText("Directorio");
        jmDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDirectorioActionPerformed(evt);
            }
        });

        BuscarClienteporCiudad.setText("Buscar Cliente por Ciudad");
        BuscarClienteporCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarClienteporCiudadActionPerformed(evt);
            }
        });
        jmDirectorio.add(BuscarClienteporCiudad);

        BuscarTelefono.setText("Buscar Telefono por Apellido");
        BuscarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTelefonoActionPerformed(evt);
            }
        });
        jmDirectorio.add(BuscarTelefono);

        jmVistaPrincipal.add(jmDirectorio);

        jmCiudades.setText("Ciudades");
        jmCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCiudadesActionPerformed(evt);
            }
        });

        AgregarCiudad.setText("Agregar Ciudad");
        AgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCiudadActionPerformed(evt);
            }
        });
        jmCiudades.add(AgregarCiudad);

        jmVistaPrincipal.add(jmCiudades);

        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jmSalir.add(Salir);

        jmVistaPrincipal.add(jmSalir);

        setJMenuBar(jmVistaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTelefonoActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        BuscarTelefonoporApellidoView bt = new BuscarTelefonoporApellidoView();
        Escritorio.add(bt);
        bt.setVisible(true);
        bt.moveToFront();
    }//GEN-LAST:event_BuscarTelefonoActionPerformed

    private void AgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCiudadActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        AgregarCiudadView agrc = new AgregarCiudadView();
        Escritorio.add(agrc);
        agrc.setVisible(true);
        agrc.moveToFront();

    }//GEN-LAST:event_AgregarCiudadActionPerformed

    private void BorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarClienteActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        BorrarCliente boc = new BorrarCliente();
        Escritorio.add(boc);
        boc.setVisible(true);
        boc.moveToFront();
    }//GEN-LAST:event_BorrarClienteActionPerformed

    private void AgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarClienteActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        AgregarClienteView acl = new AgregarClienteView();
        Escritorio.add(acl);
        acl.setVisible(true);
        acl.moveToFront();
    }//GEN-LAST:event_AgregarClienteActionPerformed

    private void BuscarClienteporCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarClienteporCiudadActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        BuscarClienteporCiudadView bucpc = new BuscarClienteporCiudadView();
        Escritorio.add(bucpc);
        bucpc.setVisible(true);
        bucpc.moveToFront();
    }//GEN-LAST:event_BuscarClienteporCiudadActionPerformed

    private void jmDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDirectorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmDirectorioActionPerformed

    private void BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarClienteActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        BuscarCliente buc = new BuscarCliente();
        Escritorio.add(buc);
        buc.setVisible(true);
        buc.moveToFront();
    }//GEN-LAST:event_BuscarClienteActionPerformed

    private void jmClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmClientesActionPerformed

    private void jmCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCiudadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCiudadesActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmSalirActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "Desea salir de la aplicación?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        Contacto c1 = new Contacto(10000001L, "Ana Laura", "González", "Buenos Aires", "Avenida Rivadavia 1234");
        Contacto c2 = new Contacto(10000002L, "Carlos Eduardo", "Martinez", "Cordoba", "Calle San Martin 567");
        Contacto c3 = new Contacto(10000003L, "Sofía", "Rodriguez", "La Plata", "Calle 54 N° 487");
        Contacto c4 = new Contacto(10000004L, "Juan Pablo", "Sánchez", "Mendoza", "Avenida Avenida Perú 987");
        Contacto c5 = new Contacto(10000005L, "Lucía", "Martinez", "Mar del Plata", "Avenidad Juan B. Justo 2345");

        directorio.agregarContacto(1145678901L, c1);
        directorio.agregarContacto(3512345678L, c2);
        directorio.agregarContacto(22142629000L, c3);
        directorio.agregarContacto(2613456789L, c4);
        directorio.agregarContacto(2235678901L, c5);

        System.out.println("Buscar contacto por teléfono número 3512345678: ");
        if (directorio.buscarContacto(3512345678L) != null) {
            System.out.println(directorio.buscarContacto(3512345678L));
        } else {
            System.out.println("El número ingresado no se encontro");
        }

        System.out.println("\nBuscar números de teléfono con apellido Martinez: ");
        System.out.println(directorio.buscarTelefono("Martinez"));

        System.out.println("\nBuscar contacto en ciudad Mendoza: ");
        System.out.println(directorio.buscarContactos("Mendoza"));

        System.out.println("\nBorrar contacto con teléfono número 3512345678: ");
        directorio.borrarContacto(3512345678L);

        System.out.println("\nBuscar contacto por teléfono número 3512345678: ");
        if (directorio.buscarContacto(3512345678L) != null) {
            System.out.println(directorio.buscarContacto(3512345678L));
        } else {
            System.out.println("El número ingresado no se encontro");
        }

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel_tp5_ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel_tp5_ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel_tp5_ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel_tp5_ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel_tp5_ej1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarCiudad;
    private javax.swing.JMenuItem AgregarCliente;
    private javax.swing.JMenuItem BorrarCliente;
    private javax.swing.JMenuItem BuscarCliente;
    private javax.swing.JMenuItem BuscarClienteporCiudad;
    private javax.swing.JMenuItem BuscarTelefono;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenu jmCiudades;
    private javax.swing.JMenu jmClientes;
    private javax.swing.JMenu jmDirectorio;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuBar jmVistaPrincipal;
    // End of variables declaration//GEN-END:variables
}
