/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp3ejercicio5;

import java.util.Set;
import java.util.TreeSet;

/**
 *
 * @author Usuario
 */
public class Panel_tp5_ej1 extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    
    public static DirectorioTelefonico directorio = new DirectorioTelefonico();
    public static Set<String> Ciudades = new TreeSet<>();
    
    public Panel_tp5_ej1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        BuscarCliente = new javax.swing.JMenuItem();
        BorrarCliente = new javax.swing.JMenuItem();
        AgregarCliente = new javax.swing.JMenuItem();
        BusquedaClienteporCiudad = new javax.swing.JMenu();
        BuscarClienteporCiudad = new javax.swing.JMenuItem();
        BuscarTelefono = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AgregarCiudad = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        jMenu1.setText("Cientes");

        BuscarCliente.setText("Buscar Cliente");
        BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(BuscarCliente);

        BorrarCliente.setText("Borrar Cliente");
        BorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(BorrarCliente);

        AgregarCliente.setText("Agregar Cliente");
        AgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(AgregarCliente);

        jMenuBar1.add(jMenu1);

        BusquedaClienteporCiudad.setText("Directorios");
        BusquedaClienteporCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaClienteporCiudadActionPerformed(evt);
            }
        });

        BuscarClienteporCiudad.setText("Buscar Cliente por Ciudad");
        BuscarClienteporCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarClienteporCiudadActionPerformed(evt);
            }
        });
        BusquedaClienteporCiudad.add(BuscarClienteporCiudad);

        BuscarTelefono.setText("Buscar Telefono por Apellido");
        BuscarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTelefonoActionPerformed(evt);
            }
        });
        BusquedaClienteporCiudad.add(BuscarTelefono);

        jMenuBar1.add(BusquedaClienteporCiudad);

        jMenu3.setText("Ciudades");

        AgregarCiudad.setText("Agregar Ciudad");
        AgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCiudadActionPerformed(evt);
            }
        });
        jMenu3.add(AgregarCiudad);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Salir");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTelefonoActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        BuscarTelefonoporApellidoView bt = new BuscarTelefonoporApellidoView();
        bt.setVisible(true);
        Escritorio.add(bt);
        Escritorio.moveToFront(bt);
    }//GEN-LAST:event_BuscarTelefonoActionPerformed

    private void AgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCiudadActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        AgregarCiudadView ac = new AgregarCiudadView();
        ac.setVisible(true);
        Escritorio.add(ac);
        Escritorio.moveToFront(ac);
        
    }//GEN-LAST:event_AgregarCiudadActionPerformed

    private void BorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarClienteActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        BorrarCliente bc = new BorrarCliente();
        bc.setVisible(true);
        Escritorio.add(bc);
        Escritorio.moveToFront(bc);
    }//GEN-LAST:event_BorrarClienteActionPerformed

    private void AgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarClienteActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        AgregarClienteView acl = new AgregarClienteView();
        acl.setVisible(true);
        Escritorio.add(acl);
        Escritorio.moveToFront(acl);
    }//GEN-LAST:event_AgregarClienteActionPerformed

    private void BuscarClienteporCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarClienteporCiudadActionPerformed
        // TODO add your handling code here:
     Escritorio.removeAll();
        Escritorio.repaint();
        BuscarClienteporCIudadView bcp = new BuscarClienteporCIudadView();
        bcp.setVisible(true);
        Escritorio.add(bcp);
        Escritorio.moveToFront(bcp);
    }//GEN-LAST:event_BuscarClienteporCiudadActionPerformed

    private void BusquedaClienteporCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaClienteporCiudadActionPerformed
        // TODO add your handling code here:
        

        
       
    }//GEN-LAST:event_BusquedaClienteporCiudadActionPerformed

    private void BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarClienteActionPerformed
        // TODO add your handling code here:
         Escritorio.removeAll();
        Escritorio.repaint();
        BuscarCliente bc = new BuscarCliente();
        bc.setVisible(true);
        Escritorio.add(bc);
        Escritorio.moveToFront(bc);
        
        
    }//GEN-LAST:event_BuscarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel_tp5_ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel_tp5_ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel_tp5_ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel_tp5_ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel_tp5_ej1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarCiudad;
    private javax.swing.JMenuItem AgregarCliente;
    private javax.swing.JMenuItem BorrarCliente;
    private javax.swing.JMenuItem BuscarCliente;
    private javax.swing.JMenuItem BuscarClienteporCiudad;
    private javax.swing.JMenuItem BuscarTelefono;
    private javax.swing.JMenu BusquedaClienteporCiudad;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
